package com.kara4k.mediagrub.model.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kara4k.mediagrub.model.database.CustomUser;
import com.kara4k.mediagrub.model.database.MediaItem;
import com.kara4k.mediagrub.model.database.Task;

import com.kara4k.mediagrub.model.database.CustomUserDao;
import com.kara4k.mediagrub.model.database.MediaItemDao;
import com.kara4k.mediagrub.model.database.TaskDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig customUserDaoConfig;
    private final DaoConfig mediaItemDaoConfig;
    private final DaoConfig taskDaoConfig;

    private final CustomUserDao customUserDao;
    private final MediaItemDao mediaItemDao;
    private final TaskDao taskDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        customUserDaoConfig = daoConfigMap.get(CustomUserDao.class).clone();
        customUserDaoConfig.initIdentityScope(type);

        mediaItemDaoConfig = daoConfigMap.get(MediaItemDao.class).clone();
        mediaItemDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        customUserDao = new CustomUserDao(customUserDaoConfig, this);
        mediaItemDao = new MediaItemDao(mediaItemDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);

        registerDao(CustomUser.class, customUserDao);
        registerDao(MediaItem.class, mediaItemDao);
        registerDao(Task.class, taskDao);
    }
    
    public void clear() {
        customUserDaoConfig.clearIdentityScope();
        mediaItemDaoConfig.clearIdentityScope();
        taskDaoConfig.clearIdentityScope();
    }

    public CustomUserDao getCustomUserDao() {
        return customUserDao;
    }

    public MediaItemDao getMediaItemDao() {
        return mediaItemDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

}
